services:
  reverse-proxy:
    image: nginx:1-alpine
    container_name: reverse-proxy
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/self-signed.cert:/etc/nginx/certs/cert.cert
      - ./proxy/self-signed.key:/etc/nginx/certs/cert.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website

  website:
    container_name: website
    restart: always
    build:
      context: website
      target: prod
    depends_on:
      - api
      - redis

  api:
    container_name: api
    restart: always
    build:
      context: crates
      target: prod
    secrets:
      - jwt-secret
      - db-password
    volumes:
      - uploads:/usr/src/app/uploads
    environment:
      JWT_SECRET: /run/secrets/jwt-secret
      POSTGRES_USER: sonne
      POSTGRES_PASSWORD: /run/secrets/db-password
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis:/data
    expose:
      - 6379

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/psql_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: sonne
      POSTGRES_PASSWORD: /run/secrets/db-password
    expose:
      - 5432

volumes:
  uploads:
  redis:
  db-data:

secrets:
  db-password:
    file: secrets/db-password
  jwt-secret:
    file: secrets/jwt-secret
