services:
  # proxy:
  #   image: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - proxy:/etc/nginx/templates

  website:
    container_name: website
    build:
      context: website
      target: dev
    command: npm run dev -- --host
    ports:
      - 5173:5173
  #   depends_on:
  #     - api
  #     - db
  #
  # api:
  #   image: rust:alpine
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - crates:/usr/src/api
  #   depends_on:
  #     - db
  #
  # db:
  #   image: postgres:alpine
  #   ports:
  #     - 5432:5432
