services:
  reverse-proxy:
    image: nginx:1-alpine
    container_name: reverse-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/self-signed.cert:/etc/nginx/certs/kleinesonne.cert
      - ./proxy/self-signed.key:/etc/nginx/certs/kleinesonne.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website

  website:
    image: node:22-alpine
    container_name: website
    user: node
    working_dir: /usr/src/app
    command: npm run dev -- --host
    environment:
      NODE_ENV: development
    volumes:
      - ./website:/usr/src/app
    ports:
      - 5173:5173
    depends_on:
      - api
      - redis

  api:
    container_name: api
    build:
      context: crates
      target: dev
    environment:
      NO_BUILD_SCRIPT: true
      JWT_SECRET: dev
      POSTGRES_USER: sonne
      POSTGRES_PASSWORD: sonne
    volumes:
      - uploads-dev:/usr/src/app/uploads
    expose:
      - 3000
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis-dev:/data
    expose:
      - 6379

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: sonne
      POSTGRES_PASSWORD: sonne
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - ./db/psql_dev_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432

volumes:
  uploads-dev:
  redis-dev:
  db-data-dev:
