services:
  reverse-proxy:
    image: nginx:1-alpine
    container_name: reverse-proxy
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website

  website:
    image: martmihkel/kleinesonne-website:latest
    container_name: website
    restart: always
    depends_on:
      - api
      - redis

  api:
    image: martmihkel/kleinesonne-api:latest
    container_name: api
    restart: always
    secrets:
      - jwt-secret
      - db-password
    volumes:
      - uploads:/usr/src/app/uploads
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    expose:
      - 6379

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/psql_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    expose:
      - 5432

volumes:
  certs:
  uploads:
  redis:
  data:
