services:
  reverse-proxy:
    image: nginx:1
    container_name: reverse-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - website

  website:
    image: node:22
    container_name: website
    user: node
    working_dir: /usr/src/app
    command: npm run dev -- --host
    volumes:
      - ./website:/usr/src/app
    ports:
      - 5173:5173
    depends_on:
      - api

  api:
    image: rust:1.79
    container_name: api
    working_dir: /usr/src/app
    command: cargo run api
    environment:
      NO_BUILD_SCRIPT: true
      UPLOAD_DIR: /usr/src/app/uploads
      JWT_SECRET: dev
      POSTGRES_USER: sonne
      POSTGRES_PASSWORD: sonne
    volumes:
      - uploads-dev:/usr/src/app/uploads
      - ./crates:/usr/src/app
    expose:
      - 3000
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: sonne
      POSTGRES_PASSWORD: sonne
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - ./db/psql_dev_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432

volumes:
  db-data-dev:
  uploads-dev:
