name: deliver
run-name: continuous delivery by ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose down
      - run: docker compose up --remove-orphans
