name: integrate
run-name: continuous integration by ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push website
        uses: docker/build-push-action@v6
        with:
          push: true
          context: website
          tags: ${{ secrets.DOCKERHUB_USER }}/kleinesonne-website:latest
      -
        name: build and push api
        uses: docker/build-push-action@v6
        with:
          push: true
          context: api
          tags: ${{ secrets.DOCKERHUB_USER }}/kleinesonne-api:latest
