name: integrate
run-name: continuous integration by ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: ./website
          tags: ${{ secrets.DOCKERHUB_USER }}/kleinesonne-website:latest
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: ./crates
          tags: ${{ secrets.DOCKERHUB_USER }}/kleinesonne-api:latest
