name: integrade and deliver
run-name: CI/CD by ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: ./website
          tags: ${{ secrets.DOCKERHUB_USER }}/kleinesonne-website:latest

  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: ./crates
          tags: ${{ secrets.DOCKERHUB_USER }}/kleinesonne-api:latest

  deliver:
    runs-on: ubuntu-latest
    needs: [build-website, build-api]
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.EC2_PRIVKEY }}
          script: |
            cd /home/${{ secrets.EC2_USER}}/kleinesonne
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PG_USER=${{ secrets.PG_USER }}" >> .env
            echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
            git pull origin master
            docker compose down
            docker compose pull
            docker compose up -d

